using System;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.IO;
using System.Linq;

namespace Todo.SourceGenerators;

public abstract class BaseRegistrationGenerator : IIncrementalGenerator
{
    protected abstract bool NodePredicate(SyntaxNode syntaxNode, CancellationToken cancellationToken);
    
    protected abstract RegistrationPair[]? Transform(GeneratorSyntaxContext context,
        CancellationToken cancellationToken);

    protected string OutputFileName() => $"{OutputClassName()}.g.cs";

    protected abstract string OutputClassName();

    protected abstract string OutputMethodName();

    protected abstract string[] OutputUsings();

    public virtual void Initialize(IncrementalGeneratorInitializationContext context)
    {   
// #if DEBUG
//         if (!System.Diagnostics.Debugger.IsAttached)
//         {
//             System.Diagnostics.Debugger.Launch();
//         }
// #endif
        
        Console.WriteLine("Starting Initialise");
        
        // Find all classes that implement ICommandFactory<CommandBase>
        var registrationPairs = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: NodePredicate,
                transform: Transform)
            .SelectMany(static (pairs, _) => pairs ?? [])
            .Collect(); 
        
        // Generate one file from all factories
        context.RegisterSourceOutput(
            registrationPairs,
            (spc, rps) =>
            {
                var source = GenerateRegistrationCode(rps);
                spc.AddSource(OutputFileName(),
                    SourceText.From(source, Encoding.UTF8));

                var path = Path.Combine("/Users/philipwhittington/Workspace", OutputFileName());
                
                //File.WriteAllText(path, source);
            });
    }
    
    protected string GenerateRegistrationCode(ImmutableArray<RegistrationPair> registrationPairs)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");

        foreach (var @using in OutputUsings())
        {
            sb.AppendLine($"using {@using};");
        }
        
        sb.AppendLine();
        sb.AppendLine("namespace Todo.DependencyInjection;"); 
        sb.AppendLine();
        sb.AppendLine($"public static class {OutputClassName()}");
        sb.AppendLine("{");
        sb.AppendLine(
            $"    public static IServiceCollection {OutputMethodName()}(this IServiceCollection services)"
        );
        sb.AppendLine("    {");
        sb.AppendLine("       return services");

        var registrationPairsOrdered = registrationPairs
            .OrderBy(x => x.Interface.Name)
            .ThenBy(x => x.Implementation.Name);
        
        foreach (var executorPair in registrationPairsOrdered)
        {
            var interfaceType = executorPair.Interface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var implementationType = executorPair.Implementation.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"        .AddSingleton<{interfaceType}, {implementationType}>()");
        }

        
        sb.AppendLine(";");
        sb.AppendLine();
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
    
}