using System;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Todo.SourceGenerators;

public abstract class BaseRegistrationGenerator : IIncrementalGenerator
{
    protected virtual bool NodePredicate(SyntaxNode syntaxNode, CancellationToken cancellationToken)
    {
        return syntaxNode is ClassDeclarationSyntax;
    }
    
    protected virtual RegistrationInfo? Transform(GeneratorSyntaxContext context, 
        CancellationToken cancellationToken)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var semanticModel = context.SemanticModel;
        
        if (semanticModel.GetDeclaredSymbol(classDecl, cancellationToken)
            is not INamedTypeSymbol classSymbol)
            return null;
        
        // Must be a concrete class (not abstract)
        if (classSymbol.IsAbstract || classSymbol.IsGenericType)
            return null;

        var isRequired = classSymbol
            .AllInterfaces
            .Any(InterfaceIsPrimaryInterface);

        if (!isRequired) return null;
        
        var interfaces = classSymbol
            .AllInterfaces
            .Where(InterfaceIsRequired)
            .ToArray();

        return interfaces.Length != 0 
            ? new RegistrationInfo(interfaces, classSymbol) 
            : null;
    }
    
    protected virtual string OutputFileName() => $"{OutputClassName()}.g.cs";

    protected abstract string OutputClassName();

    protected abstract string OutputMethodName();

    protected abstract string[] OutputUsings();
    
    protected abstract bool InterfaceIsPrimaryInterface(INamedTypeSymbol interfaceSymbol);

    protected abstract bool InterfaceIsRequired(INamedTypeSymbol interfaceSymbol);

    public virtual void Initialize(IncrementalGeneratorInitializationContext context)
    {   
        Console.WriteLine("Starting Initialise");
        
        // Find all classes that implement ICommandFactory<CommandBase>
        var registrationPairs = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: NodePredicate,
                transform: Transform)
            .Where(x => x is not null)
            .Collect(); 
        
        // Generate one file from all factories
        context.RegisterSourceOutput(
            registrationPairs,
            (spc, rps) =>
            {
                var source = GenerateRegistrationCode(rps);
                spc.AddSource(OutputFileName(),
                    SourceText.From(source, Encoding.UTF8));

                var path = Path.Combine("/Users/philipwhittington/Workspace", OutputFileName());
            });
    }
    
    protected string GenerateRegistrationCode(ImmutableArray<RegistrationInfo> registrationPairs)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");

        foreach (var @using in OutputUsings())
        {
            sb.AppendLine($"using {@using};");
        }
        
        sb.AppendLine();
        sb.AppendLine("namespace Todo;"); 
        sb.AppendLine();
        sb.AppendLine($"public static class {OutputClassName()}");
        sb.AppendLine("{");
        sb.AppendLine(
            $"    public static IServiceCollection {OutputMethodName()}(this IServiceCollection services)"
        );
        sb.AppendLine("    {");
        sb.AppendLine("       return services");

        var registrationPairsOrdered = registrationPairs
            .OrderBy(x => x.Implementation.Name);
        
        foreach (var executorPair in registrationPairsOrdered)
        {
            var displayStrings = executorPair.Interfaces
                .Select(x => x.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .Select(x => $"typeof({x})");

            var interfaceArrayStr = $"new Type [] {{{string.Join(",", displayStrings)}}}";
            
            var implementationType = executorPair.Implementation.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var implementationTypeWithTypeOf = $"typeof({implementationType})";
            
            sb.AppendLine($"        .RegisterSeveralInterfaces({interfaceArrayStr}, {implementationTypeWithTypeOf})");
        }
        
        sb.AppendLine(";");
        sb.AppendLine();
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
    
}