using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;

namespace Todo.SourceGenerators;

public abstract class BaseRegistrationGenerator(
    string commandFactoryInterface,
    string? commandBaseTypeName,
    string outputFileName,
    string className,
    string methodName,
    ImmutableArray<string> usings)
{
    protected string CommandFactoryInterface { get; } = commandFactoryInterface;

    protected string? CommandBaseTypeName { get; } = commandBaseTypeName;

    protected string OutputFileName { get; } = outputFileName;

    protected string ClassName { get; } = className;

    protected string MethodName { get; } = methodName;

    protected ImmutableArray<string> Usings { get; } = usings;

    // protected abstract string GenerateRegistrationCode(ImmutableArray<INamedTypeSymbol> factories);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes that implement ICommandFactory<CommandBase>
        var factories = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: (ctx, ct) => GetFactoryIfMatches(ctx, ct)
            )
            .Where(static m => m is not null)
            .Collect(); // Collect all results into one ImmutableArray

        // Generate one file from all factories
        context.RegisterSourceOutput(
            factories,
            (spc, factoriesArray) =>
            {
                var source = GenerateRegistrationCode(factoriesArray!);
                spc.AddSource(OutputFileName,
                    SourceText.From(source, Encoding.UTF8)
                );
            }
        );
    }
    
    protected static bool IsOrInheritsFrom(ITypeSymbol type, string baseName)
    {
        var current = type;
        while (current != null)
        {
            if (current.Name == baseName)
                return true;
            current = current.BaseType;
        }
        return false;
    }
    
    protected INamedTypeSymbol? GetFactoryIfMatches(
        GeneratorSyntaxContext context,
        CancellationToken cancellationToken)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var semanticModel = context.SemanticModel;

        if (
            semanticModel.GetDeclaredSymbol(classDecl, cancellationToken)
            is not INamedTypeSymbol classSymbol
        )
            return null;

        // Must be a concrete class (not abstract)
        if (classSymbol.IsAbstract || classSymbol.IsGenericType)
            return null;

        foreach (var iface in classSymbol.AllInterfaces)
        {
            if (
                iface.OriginalDefinition.Name == CommandFactoryInterface
                && iface.TypeArguments.Length == 1
            )
            {
                var typeArg = iface.TypeArguments[0];
                
                if (CommandBaseTypeName is null ||
                    IsOrInheritsFrom(typeArg, CommandBaseTypeName))
                {
                    return classSymbol;
                }
            }
        }

        return null;
    }
    
    protected string GenerateRegistrationCode(
        ImmutableArray<ExecutorPair> executorPairs)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");

        foreach (var @using in Usings)
        {
            sb.AppendLine($"using {@using};");
        }
        
        sb.AppendLine();
        sb.AppendLine("namespace Todo.DependencyInjection;"); 
        sb.AppendLine();
        sb.AppendLine($"public static class {ClassName}");
        sb.AppendLine("{");
        sb.AppendLine(
            $"    public static IServiceCollection {MethodName}(this IServiceCollection services)"
        );
        sb.AppendLine("    {");
        sb.AppendLine("       return services");

        var executorPairsOrdered = executorPairs
            .OrderBy(x => x.Interface)
            .ThenBy(x => x.Implementation);
        
        foreach (var executorPair in executorPairsOrdered)
        {
            var interfaceType = executorPair.Interface!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var implementationType = executorPair.Implementation!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"        .AddSingleton<{interfaceType}, {implementationType}>()");
        }

        
        sb.AppendLine(";");
        sb.AppendLine();
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
    
}