using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
// ReSharper disable InconsistentNaming

namespace Todo.SourceGenerators;

[Generator]
public class CommandExecutorRegistrationGenerator() 
    : BaseRegistrationGenerator(_CommandFactoryInterface, _CommandBaseTypeName, _OutputFileName,
    _ClassName, _MethodName, _Usings), 
        IIncrementalGenerator
{
    private const string _CommandFactoryInterface = "ICommandExecutor";
    private const string? _CommandBaseTypeName = null;
    private const string _OutputFileName = "CommandExecutorRegistrations.g.cs";
    private const string _ClassName = "CommandExecutorRegistrations";
    private const string _MethodName = "AddCommandExecutors";

    private static readonly ImmutableArray<string> _Usings = ImmutableArray.Create(
        "Todo.Execution",
        "Todo.Contracts.Services.Execution");

    // protected override string GenerateRegistrationCode(ImmutableArray<INamedTypeSymbol> factories)
    // {
    //     var sb = new StringBuilder();
    //
    //     sb.AppendLine("// <auto-generated/>");
    //     sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
    //     sb.AppendLine("using Todo.Execution;");
    //     sb.AppendLine("using Todo.Contracts.Services.Execution;");
    //     sb.AppendLine();
    //     sb.AppendLine("namespace Todo.DependencyInjection;"); 
    //     sb.AppendLine();
    //     sb.AppendLine("public static class CommandExecutorRegistrations");
    //     sb.AppendLine("{");
    //     sb.AppendLine(
    //         "    public static IServiceCollection AddCommandFactoriesExecutors(this IServiceCollection services)"
    //     );
    //     sb.AppendLine("    {");
    //     sb.AppendLine("       return services");
    //
    //     foreach (var factory in factories.OrderBy(f => f.Name))
    //     {
    //         var fullName = factory.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    //         sb.AppendLine($"        .AddSingleton<ICommandExecutor, {fullName}>()");
    //     }
    //
    //     sb.AppendLine(";");
    //     sb.AppendLine();
    //     sb.AppendLine("    }");
    //     sb.AppendLine("}");
    //
    //     return sb.ToString();
    // }
}
