using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
// ReSharper disable InconsistentNaming

namespace Todo.SourceGenerators;

[Generator]
public class CommandFactoryRegistrationGenerator() 
    : BaseRegistrationGenerator(_CommandFactoryInterface, _CommandBaseTypeName, _OutputFileName,
            _ClassName, _MethodName, _Usings),  IIncrementalGenerator
{
    
    private const string _CommandFactoryInterface = "ICommandFactory";
    private const string _CommandBaseTypeName = "CommandBase";
    private const string _OutputFileName = "CommandFactoryRegistrations.g.cs";

    private const string _ClassName = "CommandFactoryRegistrations";
    private const string _MethodName = "AddCommandFactories";

    private static readonly ImmutableArray<string> _Usings = ImmutableArray.Create(
        "Todo.Contracts.Services.CommandFactories;",
        "Todo.Contracts.Data.Commands;");
    
    // protected override string GenerateRegistrationCode(ImmutableArray<INamedTypeSymbol> factories)
    // {
    //     var sb = new StringBuilder();
    //
    //     sb.AppendLine("// <auto-generated/>");
    //     sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
    //     sb.AppendLine();
    //     sb.AppendLine("namespace Todo.DependencyInjection;");
    //     sb.AppendLine();
    //     sb.AppendLine("public static class CommandFactoryRegistrations");
    //     sb.AppendLine("{");
    //     sb.AppendLine(
    //         "    public static IServiceCollection AddCommandFactories(this IServiceCollection services)"
    //     );
    //     sb.AppendLine("    {");
    //     sb.AppendLine("       return services");
    //
    //     foreach (var factory in factories.OrderBy(f => f.Name))
    //     {
    //         var fullName = factory.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    //         sb.AppendLine($"        .AddSingleton<ICommandFactory<CommandBase>, {fullName}>()");
    //     }
    //
    //     sb.AppendLine(";");
    //     sb.AppendLine();
    //     sb.AppendLine("    }");
    //     sb.AppendLine("}");
    //
    //     return sb.ToString();
    // }
}
