using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Todo.SourceGenerators;

[Generator]
public class CommandFactoryRegistrationGenerator : IIncrementalGenerator
{
    private const string CommandFactoryInterface = "ICommandFactory";
    private const string CommandBaseTypeName = "CommandBase";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes that implement ICommandFactory<CommandBase>
        var factories = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: (ctx, ct) => GetFactoryIfMatches(ctx, ct)
            )
            .Where(static m => m is not null)
            .Collect(); // Collect all results into one ImmutableArray

        // Generate one file from all factories
        context.RegisterSourceOutput(
            factories,
            static (spc, factoriesArray) =>
            {
                var source = GenerateRegistrationCode(factoriesArray!);
                spc.AddSource(
                    "CommandFactoryRegistrations.g.cs",
                    SourceText.From(source, Encoding.UTF8)
                );
            }
        );
    }

    private static INamedTypeSymbol? GetFactoryIfMatches(
        GeneratorSyntaxContext context,
        CancellationToken cancellationToken)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var semanticModel = context.SemanticModel;

        if (
            semanticModel.GetDeclaredSymbol(classDecl, cancellationToken)
            is not INamedTypeSymbol classSymbol
        )
            return null;

        // Must be a concrete class (not abstract)
        if (classSymbol.IsAbstract || classSymbol.IsGenericType)
            return null;

        foreach (var iface in classSymbol.AllInterfaces)
        {
            if (
                iface.OriginalDefinition.Name == CommandFactoryInterface
                && iface.TypeArguments.Length == 1
            )
            {
                var typeArg = iface.TypeArguments[0];

                if (IsOrInheritsFrom(typeArg, CommandBaseTypeName))
                {
                    return classSymbol;
                }
            }
        }

        return null;
    }

    private static bool IsOrInheritsFrom(ITypeSymbol type, string baseName)
    {
        ITypeSymbol? current = type;
        while (current != null)
        {
            if (current.Name == baseName)
                return true;
            current = current.BaseType;
        }
        return false;
    }

    private static string GenerateRegistrationCode(ImmutableArray<INamedTypeSymbol> factories)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Todo.Contracts.Services.CommandFactories;");
        sb.AppendLine("using Todo.Contracts.Data.Commands;");

        sb.AppendLine();
        sb.AppendLine("namespace Todo.DependencyInjection;"); // ← Change this to your desired namespace
        sb.AppendLine();
        sb.AppendLine("public static class CommandFactoryRegistrations");
        sb.AppendLine("{");
        sb.AppendLine(
            "    public static IServiceCollection AddCommandFactories(this IServiceCollection services)"
        );
        sb.AppendLine("    {");
        sb.AppendLine("       return services");

        foreach (var factory in factories.OrderBy(f => f.Name))
        {
            var fullName = factory.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"        .AddSingleton<ICommandFactory<CommandBase>, {fullName}>()");
        }
    
        sb.AppendLine(";");
        sb.AppendLine();
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
