using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Todo.SourceGenerators;

[Generator]
public class CommandExecutorRegistrationGenerator: BaseRegistrationGenerator
{
    protected override bool NodePredicate(SyntaxNode syntaxNode, CancellationToken cancellationToken)
    {
        return syntaxNode is ClassDeclarationSyntax;
    }

    protected override RegistrationPair[]? Transform(GeneratorSyntaxContext context, 
        CancellationToken cancellationToken)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var semanticModel = context.SemanticModel;
        
        if (semanticModel.GetDeclaredSymbol(classDecl, cancellationToken)
            is not INamedTypeSymbol classSymbol)
            return null;
        
        // Must be a concrete class (not abstract)
        if (classSymbol.IsAbstract || classSymbol.IsGenericType)
            return null;
        
        foreach (var iface in classSymbol.AllInterfaces)
        {
            if (iface.OriginalDefinition.Name == "ICommandExecutor"
                && iface.TypeArguments.Length == 1)
            {
                return
                [
                    new RegistrationPair(iface, classSymbol)
                ];
            }
        }
        
        return null;
    }

    // protected INamedTypeSymbol? GetFactoryIfMatches(
    //     GeneratorSyntaxContext context,
    //     CancellationToken cancellationToken)
    // {
    //     var classDecl = (ClassDeclarationSyntax)context.Node;
    //     var semanticModel = context.SemanticModel;
    //
    //     if (
    //         semanticModel.GetDeclaredSymbol(classDecl, cancellationToken)
    //         is not INamedTypeSymbol classSymbol
    //     )
    //         return null;
    //
    //     // Must be a concrete class (not abstract)
    //     if (classSymbol.IsAbstract || classSymbol.IsGenericType)
    //         return null;
    //
    //     foreach (var iface in classSymbol.AllInterfaces)
    //     {
    //         if (
    //             iface.OriginalDefinition.Name == CommandFactoryInterface
    //             && iface.TypeArguments.Length == 1
    //         )
    //         {
    //             var typeArg = iface.TypeArguments[0];
    //             
    //             if (CommandBaseTypeName is null ||
    //                 IsOrInheritsFrom(typeArg, CommandBaseTypeName))
    //             {
    //                 return classSymbol;
    //             }
    //         }
    //     }
    //
    //     return null;
    // }
    
    protected override string OutputFileName() => "CommandExecutorRegistrations.g.cs";

    protected override string OutputClassName() => "CommandExecutorRegistrations";

    protected override string OutputMethodName() => "AddCommandExecutors";

    protected override string[] OutputUsings() => new string[]
    {
        "Todo.Execution",
        "Todo.Contracts.Services.Execution"
    };

    // protected override string GenerateRegistrationCode(ImmutableArray<INamedTypeSymbol> factories)
    // {
    //     var sb = new StringBuilder();
    //
    //     sb.AppendLine("// <auto-generated/>");
    //     sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
    //     sb.AppendLine("using Todo.Execution;");
    //     sb.AppendLine("using Todo.Contracts.Services.Execution;");
    //     sb.AppendLine();
    //     sb.AppendLine("namespace Todo.DependencyInjection;"); 
    //     sb.AppendLine();
    //     sb.AppendLine("public static class CommandExecutorRegistrations");
    //     sb.AppendLine("{");
    //     sb.AppendLine(
    //         "    public static IServiceCollection AddCommandFactoriesExecutors(this IServiceCollection services)"
    //     );
    //     sb.AppendLine("    {");
    //     sb.AppendLine("       return services");
    //
    //     foreach (var factory in factories.OrderBy(f => f.Name))
    //     {
    //         var fullName = factory.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    //         sb.AppendLine($"        .AddSingleton<ICommandExecutor, {fullName}>()");
    //     }
    //
    //     sb.AppendLine(";");
    //     sb.AppendLine();
    //     sb.AppendLine("    }");
    //     sb.AppendLine("}");
    //
    //     return sb.ToString();
    // }
    
}
