using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Todo.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class ServiceRegistrationGenerator : IIncrementalGenerator
{
    private const string TargetInterface = "ICommandExecutor"; // ← change if needed
    private const string TargetInterfaceFull = "Todo.Contracts.ICommandExecutor"; // optional, for safety

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        
        // Find all class declarations
        var classesProvider = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) =>
                {
                    var classDecl = (ClassDeclarationSyntax)ctx.Node;
                    var semanticModel = ctx.SemanticModel;
                    var typeSymbol =
                        semanticModel.GetDeclaredSymbol(classDecl, ct) as INamedTypeSymbol;

                    if (typeSymbol is null || typeSymbol.IsAbstract)
                        return null;

                    // Check if it implements the target interface
                    var implementsInterface = typeSymbol.AllInterfaces.Any(i =>
                        i.Name == TargetInterface || i.ToDisplayString() == TargetInterfaceFull
                    );

                    if (!implementsInterface)
                        return null;

                    // Skip base classes you don't want to register (e.g. CommandExecutorBase)
                    if (typeSymbol.Name == "CommandExecutorBase")
                        return null;

                    return typeSymbol;
                }
            )
            .Where(static x => x is not null);

        // Combine with compilation for safety
        var provider = context.CompilationProvider.Combine(classesProvider.Collect());
        
        // Generate the registration code
        context.RegisterSourceOutput(
            provider,
            static (spc, tuple) =>
            {
                var (compilation, implementations) = tuple;
                
                if (implementations.IsDefaultOrEmpty)
                    return;

                var sb = new StringBuilder();
                sb.AppendLine("// PDW woz ere");
                sb.AppendLine("// <auto-generated />");
                sb.AppendLine("// This file was generated by ServiceRegistrationGenerator");
                sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
                sb.AppendLine();
                sb.AppendLine("public static partial class ServiceCollectionExtensions");
                sb.AppendLine("{");
                sb.AppendLine(
                    "    public static IServiceCollection AddMyAppServices(this IServiceCollection services)"
                );
                sb.AppendLine("    {");

                foreach (var impl in implementations)
                {
                    if (impl is null) continue;
                    
                    var interfaceName = impl
                        .AllInterfaces.First(i =>
                            i.Name == TargetInterface || i.ToDisplayString() == TargetInterfaceFull
                        )
                        .ToDisplayString();

                    sb.AppendLine(
                        $"        services.AddSingleton<{interfaceName}, {impl.ToDisplayString()}>();"
                    );
                }

                sb.AppendLine("        return services;");
                sb.AppendLine("    }");
                sb.AppendLine("}");

                spc.AddSource(
                    "ServiceCollectionExtensions.g.cs",
                    SourceText.From(sb.ToString(), Encoding.UTF8)
                );
            }
        );
    }
}

