using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;
using System.Linq;
using System.Threading;

namespace Todo.SourceGenerators;

[Generator]
public class SpecificCommandExecutorRegistrationGenerator : IIncrementalGenerator
{
    private const string CommandExecutorInterface = "ICommandExecutor";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var executors = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => 
                    node is InterfaceDeclarationSyntax || node is ClassDeclarationSyntax,
                transform: (ctx, ct) => GetExecutorPair(ctx, ct))
            .Where(static m => m is not null)
            .Collect();

        context.RegisterSourceOutput(executors, static (spc, pairs) =>
        {
            var source = GenerateRegistrationCode(pairs!);
            spc.AddSource("SpecificCommandExecutorRegistrations.g.cs", 
                SourceText.From(source, Encoding.UTF8));
        });
    }

    private static ExecutorPair? GetExecutorPair(GeneratorSyntaxContext context, CancellationToken ct)
    {
        var semanticModel = context.SemanticModel;

        if (context.Node is InterfaceDeclarationSyntax ifaceDecl)
        {
            if (semanticModel.GetDeclaredSymbol(ifaceDecl, ct) is not INamedTypeSymbol iface)
                return null;

            var commandType = GetCommandTypeFromExecutorInterface(iface);
            if (commandType is null)
                return null;

            return new ExecutorPair(iface, commandType, null); 

        }
        else if (context.Node is ClassDeclarationSyntax classDecl)
        {
            if (semanticModel.GetDeclaredSymbol(classDecl, ct) is not INamedTypeSymbol cls)
                return null;

            return new ExecutorPair(null, cls, null);
        }

        return null;
    }

    private static ITypeSymbol? GetCommandTypeFromExecutorInterface(INamedTypeSymbol iface)
    {
        foreach (var baseIface in iface.AllInterfaces)
        {
            if (baseIface.OriginalDefinition.Name == CommandExecutorInterface &&
                baseIface.TypeArguments.Length == 1)
            {
                return baseIface.TypeArguments[0];
            }
        }
        return null;
    }

    private static string GenerateRegistrationCode(ImmutableArray<ExecutorPair> items)
    {
        var interfaces = items.Where(i => i.Interface is not null).ToList();
        var implementations = items.Where(i => i.Implementation is not null)
                                  .ToDictionary(i => i.Implementation!.Name, i => i.Implementation);

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Todo.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("public static class SpecificCommandExecutorRegistrations");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddSpecificCommandExecutors(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var ifacePair in interfaces.OrderBy(i => i.Interface!.Name))
        {
            var iface = ifacePair.Interface!;
            var expectedImplName = iface.Name.Substring(1); // Remove 'I' prefix

            if (implementations.TryGetValue(expectedImplName, out var impl))
            {
                var ifaceFull = iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var implFull = impl.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                sb.AppendLine($"        services.AddSingleton<{ifaceFull}, {implFull}>();");
            }
            else
            {
                // Optional: emit a comment if implementation is missing
                sb.AppendLine($"        // TODO: Missing implementation for {iface.Name}");
            }
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }


}