<?xml version="1.0" encoding="UTF-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <!-- Standard assembly properties -->
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Todo</RootNamespace>
        <AssemblyName>todo</AssemblyName>
        <LangVersion>14</LangVersion>
        <Nullable>enable</Nullable>
        <TieredPGO>false</TieredPGO>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
        <CompilerGeneratedFilesOutputPath>obj/Generated</CompilerGeneratedFilesOutputPath>
        <EnableSingleFileAnalyzer>true</EnableSingleFileAnalyzer>
    </PropertyGroup>
    <!-- Treat warnings as errors ONLY in Release -->
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <PublishAot>true</PublishAot>
        <OptimizationPreference>Speed</OptimizationPreference>
        <PublishReadyToRun>true</PublishReadyToRun>
        <TieredCompilation>false</TieredCompilation>
        <DebugSymbols>false</DebugSymbols>
        <DebugType>none</DebugType>
        <PublishSymbols>false</PublishSymbols>
        <CopyDebugSymbolsToPublishDirectory>false</CopyDebugSymbolsToPublishDirectory>
    </PropertyGroup>
    <!-- Make classes marked as internal available to the test project -->
    <ItemGroup>
        <InternalsVisibleTo Include="Todo.Tests" />
    </ItemGroup>
    <!-- nuget references -->
    <ItemGroup>
        <PackageReference Include="LibGit2Sharp"
                          Version="0.31.0" />
        <PackageReference Include="Markdig"
                          Version="1.1.2" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console"
                          Version="10.0.5" />
    </ItemGroup>
    <!-- Embedded templates -->
    <ItemGroup>
        <!-- Markdown templates -->
        <None Remove="day-list-template.md" />
        <EmbeddedResource Include="day-list-template.md" />
        <None Remove="topic-list-template.md" />
        <EmbeddedResource Include="topic-list-template.md" />
        <!-- HTML templates -->
        <None Remove="list-template.html" />
        <EmbeddedResource Include="list-template.html" />
        <None Remove="graph-template.html" />
        <EmbeddedResource Include="graph-template.html" />
        <!-- Settings templates -->
        <None Remove="todo-settings.json" />
        <EmbeddedResource Include="todo-settings.json" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Todo.Contracts\Todo.Contracts.csproj" />
        <ProjectReference Include="..\Todo.SourceGenerators\Todo.SourceGenerators.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false" />
    </ItemGroup>
    <!-- Pre-build event to populate the above files -->
    <PropertyGroup>
        <CurrentDate>$([System.DateTime]::Now.ToString(yyyy-MM-dd HH:mm:ss))</CurrentDate>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <Target Name="GenerateBuildInfo"
            BeforeTargets="BeforeCompile">
        <!-- Git describe -->
        <Exec Command="git describe --long --dirty --tags --always"
              ConsoleToMsBuild="true"
              ContinueOnError="true"
              IgnoreExitCode="true">
            <Output TaskParameter="ConsoleOutput" PropertyName="GitDescribe" />
        </Exec>

        <!-- Branches that point to current HEAD -->
        <Exec Command="git branch --points-at HEAD --format='%(refname:short)'"
              ConsoleToMsBuild="true"
              ContinueOnError="true"
              IgnoreExitCode="true">
          <Output TaskParameter="ConsoleOutput" PropertyName="GitBranches" />
        </Exec>

        <!-- Tags that point to current HEAD -->
        <Exec Command="git tag --points-at HEAD"
              ConsoleToMsBuild="true"
              ContinueOnError="true"
              IgnoreExitCode="true">
          <Output TaskParameter="ConsoleOutput" PropertyName="GitTags" />
        </Exec>

        <!-- Worktree changes -->
        <Exec Command="git status --porcelain"
              ConsoleToMsBuild="true"
              ContinueOnError="true"
              IgnoreExitCode="true">
          <Output TaskParameter="ConsoleOutput" PropertyName="GitWorktreeChanges" />
        </Exec>

        <!-- Windows: Build time -->
        <Exec Command="powershell -NoProfile -Command &quot;Get-Date -Format 'yyyy-MM-dd HH:mm:sszzz'&quot;"
              ConsoleToMsBuild="true"
              ContinueOnError="true"
              IgnoreExitCode="true"
              Condition="'$(OS)' == 'Windows_NT'">
            <Output TaskParameter="ConsoleOutput"
                    PropertyName="BuildTime" />
        </Exec>
        <!-- Linux/MacOS: Build time -->
        <Exec Command="date '+%Y-%m-%d %H:%M:%S%z'"
              ConsoleToMsBuild="true"
              ContinueOnError="true"
              IgnoreExitCode="true"
              Condition="'$(OS)' != 'Windows_NT'">
            <Output TaskParameter="ConsoleOutput"
                    PropertyName="BuildTime" />
        </Exec>
        <ItemGroup>
            <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
                <_Parameter1>GitDescribe</_Parameter1>
                <_Parameter2>$(GitDescribe)</_Parameter2>
            </AssemblyAttribute>

            <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
                <_Parameter1>GitBranches</_Parameter1>
                <_Parameter2>$(GitBranches)</_Parameter2>
            </AssemblyAttribute>

            <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
                <_Parameter1>GitTags</_Parameter1>
                <_Parameter2>$(GitTags)</_Parameter2>
            </AssemblyAttribute>

            <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
                <_Parameter1>GitWorktreeChanges</_Parameter1>
                <_Parameter2>$(GitWorktreeChanges)</_Parameter2>
            </AssemblyAttribute>

            <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
                <_Parameter1>BuildTime</_Parameter1>
                <_Parameter2>$(BuildTime)</_Parameter2>
            </AssemblyAttribute>

            <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
                <_Parameter1>BuildConfiguration</_Parameter1>
                <_Parameter2>$(Configuration)</_Parameter2>
            </AssemblyAttribute>

            <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
                <_Parameter1>DebugType</_Parameter1>
                <_Parameter2>$(DebugType)</_Parameter2>
            </AssemblyAttribute>

            <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
                <_Parameter1>OptimizationPreference</_Parameter1>
                <_Parameter2>$(OptimizationPreference)</_Parameter2>
            </AssemblyAttribute>

            <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
                <_Parameter1>PublishAot</_Parameter1>
                <_Parameter2>$(PublishAot)</_Parameter2>
            </AssemblyAttribute>

            <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
                <_Parameter1>PublishDir</_Parameter1>
                <_Parameter2>$(PublishDir)</_Parameter2>
            </AssemblyAttribute>

            <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
                <_Parameter1>PublishReadyToRun</_Parameter1>
                <_Parameter2>$(PublishReadyToRun)</_Parameter2>
            </AssemblyAttribute>

            <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
                <_Parameter1>PublishReadyToRunComposite</_Parameter1>
                <_Parameter2>$(PublishReadyToRunComposite)</_Parameter2>
            </AssemblyAttribute>

            <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
                <_Parameter1>PublishSingleFile</_Parameter1>
                <_Parameter2>$(PublishSingleFile)</_Parameter2>
            </AssemblyAttribute>

            <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
                <_Parameter1>PublishTrimmed</_Parameter1>
                <_Parameter2>$(PublishTrimmed)</_Parameter2>
            </AssemblyAttribute>

            <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
                <_Parameter1>RuntimeIdentifier</_Parameter1>
                <_Parameter2>$(RuntimeIdentifier)</_Parameter2>
            </AssemblyAttribute>

            <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
                <_Parameter1>SelfContained</_Parameter1>
                <_Parameter2>$(SelfContained)</_Parameter2>
            </AssemblyAttribute>

            <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
                <_Parameter1>SourceRevisionId</_Parameter1>
                <_Parameter2>$(SourceRevisionId)</_Parameter2>
            </AssemblyAttribute>

            <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
                <_Parameter1>TargetFramework</_Parameter1>
                <_Parameter2>$(TargetFramework)</_Parameter2>
            </AssemblyAttribute>

            <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
                <_Parameter1>TieredCompilation</_Parameter1>
                <_Parameter2>$(TieredCompilation)</_Parameter2>
            </AssemblyAttribute>
        </ItemGroup>
    </Target>
    <Target Name="RemovePdbsFromPublish"
            AfterTargets="ComputeResolvedFilesToPublishList">
        <ItemGroup>
            <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)"
                                   Condition="'%(Extension)' == '.pdb'" />
        </ItemGroup>
    </Target>
</Project>
